my_project:
  outputs:
    dev:
      dbname: airflow
      host: postgres
      pass: airflow
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: airflow
  target: dev
